version: '3'
services:
  kanitha:
    image: "kanitha9/my-flask-app"
    container_name: kanitha_container
    restart: always
    ports:
      - "8888:5000"
  naveen:
    image: "naveenkumarb26/flask"
    container_name: naveen_container
    restart: always
    ports:
      - "7777:5000"
